# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth_port',
            field=models.IntegerField(null=True, verbose_name='Vlan Id'),
        ),
        migrations.AlterField(
            model_name='host',
            name='last_ping',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ping_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Undetermined', 'Undetermined'), ('Fail', 'Failed')], default='Undetermined', max_length=2),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='netmask',
            field=models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4'),
        ),
    ]
