# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0002_auto_20161010_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
