# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_manager', '0005_auto_20161010_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth_port',
            field=models.IntegerField(default=0, verbose_name='Vlan Id'),
        ),
    ]
